name: Restore Cache Action
description: Restore cached node packages and modules

inputs:
  packages:
    description: 'Flag to cache or not node setup packages'
    default: 'false'
  modules:
    description: 'Flag to cache or not node install modules'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup and node packages
      if: ${{ inputs.packages }} == 'true'
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - name: Restore Cache
      uses: actions/cache/restore@v4
      id: restore-cache-node-modules
      if: ${{ inputs.modules }} == 'true'
      with:
        key: node-modules-{{ hashFiles('package-lock.json') }}
        path: |
          ./node_modules/*
          ./frontend/node_modules/*
          ./backend/node_modules/*
        fail-on-cache-miss: 'true'
    - name: Exit if no cache found for node modules
      if: steps.restore-cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo Cache for node modules was not restored
        exit 1
